const $=s=>document.querySelector(s);let score=0,level=1,lives=3,time=30,timer,spawnTimer,running=false,audioOn=true;
const cfg={easy:[1800,1500],normal:[1350,1050],hard:[950,750]};
let audioCtx=null,scanSoundTimer=null;
function ctx(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function tone(f=500,d=.08,vol=.08){if(!audioOn)return;const a=ctx(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.type="sine";o.frequency.value=f;g.gain.setValueAtTime(vol,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.start();o.stop(a.currentTime+d)}
function scanPing(){if(!running||!audioOn)return;tone(720,.045,.025);setTimeout(()=>{if(running&&audioOn)tone(980,.035,.014)},90)}
function startScanSound(){clearInterval(scanSoundTimer);scanPing();scanSoundTimer=setInterval(scanPing,1100)}
function stopScanSound(){clearInterval(scanSoundTimer);scanSoundTimer=null}
function update(){level=Math.floor(score/100)+1;$("#score").textContent=score;$("#level").textContent=level;$("#lives").textContent="♥".repeat(lives);$("#time").textContent=time;$("#sweep").style.animationDuration=Math.max(1.25,4-level*.12)+"s"}
function spawn(){if(!running)return;const box=$("#contacts"),target=Math.random()<.35,b=document.createElement("button");b.className="contact"+(target?" target":"");const r=Math.sqrt(Math.random())*43,a=Math.random()*Math.PI*2;b.style.left=50+Math.cos(a)*r+"%";b.style.top=50+Math.sin(a)*r+"%";b.onclick=e=>{e.stopPropagation();if(target){score+=20;$("#status").textContent="CIBLE CONFIRMÉE +20";tone(900)}else{lives--;$("#status").textContent="LEURRE !";tone(180,.18)}b.remove();update();if(lives<=0)end()};box.appendChild(b);const diff=$("#difficulty").value,[life]=cfg[diff];setTimeout(()=>{if(b.isConnected){if(target){lives--;$("#status").textContent="CIBLE PERDUE";tone(160,.2);update();if(lives<=0)end()}b.remove()}},Math.max(550,life-level*35));const delay=Math.max(420,cfg[diff][1]-level*30);spawnTimer=setTimeout(spawn,delay)}
function start(){score=0;level=1;lives=3;time=30;running=true;$("#home").hidden=true;$("#game").hidden=false;$("#contacts").innerHTML="";update();spawn();startScanSound();timer=setInterval(()=>{time--;update();if(time<=0)end()},1000)}
function end(){if(!running)return;running=false;clearInterval(timer);clearTimeout(spawnTimer);stopScanSound();$("#contacts").innerHTML="";$("#finalScore").textContent=score;$("#finalLevel").textContent=level;$("#over").showModal();tone(260,.35)}
function home(){$("#over").close();$("#game").hidden=true;$("#home").hidden=false}
$("#start").onclick=start;$("#again").onclick=()=>{$("#over").close();start()};$("#back").onclick=home;$("#quit").onclick=()=>{running=false;clearInterval(timer);clearTimeout(spawnTimer);stopScanSound();home()};$("#sound").onclick=()=>{audioOn=!audioOn;$("#sound").textContent=audioOn?"🔊":"🔇";if(audioOn){ctx();if(running)startScanSound()}else stopScanSound()};